name: Zip Lambda and upload to S3 bucket
on: [push]

permissions:
  id-token: write
  contents: read
  pull-requests: write
  repository-projects: write
jobs:
  zip-lambda-function:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Zip da-ayr-rest-api lambda function 
      run:  |
        pwd
        ./package_lambda.sh da-ayr-rest-api  aws_lambda.py
    - name: Check files in the da-ayr-rest-api-auth directory 
      run: |
        cd da-ayr-rest-api
        ls

